<!DOCTYPE html>
<html>
<head>
  <title>DataTable</title>


</head>
<body>
      <div class="col-md-5" align="right">
      <a href="{{ route('pdf') }}" class="btn btn-success">Save as PDF</a>
    </div>
  <table id="tanvir" class="display">
    <thead>
        <tr>
          <th>ID</th>
          <th>Property Name</th>
          <th>Location</th>
          <th>Price($)</th>
          <th>Address</th>
          <th>Owner</th>
          <th>Agent Name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
                <tr>
            <td>1</td>
            <td>Villa</td>
            <td>Rangamati</td>
            <td>5252532</td>
            <td>Chittagong</td>
            <td>Tanvir</td>
            <td>Tanvir</td>
        </tr>
    </tbody>
</table>

</body>
</html>